spring:
  datasource:
    dynamic:
      primary: users
      datasource:
        orders:
          url: jdbc:mysql:///test_orders?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: password
        users:
          url: jdbc:mysql:///test_users?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: password
# mybatis ????
mybatis:
  config-location: classpath:mybatis-config.xml # ?? MyBatis ??????
  mapper-locations: classpath:mapper/*.xml # ?? Mapper XML ??
  type-aliases-package: com.example.dynamicdatasource.dataobject # ??????????

