
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: #
    database: 0 #
    timeout: 0 #
    # ?? RedisProperties.Jedis ???
    jedis:
      pool:
        max-active: 8 # ???????????? 8 ????????????
        max-idle: 8 # ????????????????? 8 ????????????
        min-idle: 0 # ????????????????? 0 ????? 0 ? ???
        max-wait: -1 # ????????????????????? -1 ???????
