spring:
  # datasource ???????
  datasource:
    url: jdbc:mysql:///test2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

# mybatis-plus ????
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ????? true ????????????
  global-config:
    db-config:
      id-type: auto # ID ????
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.mybatisplus.dataobject

logging:
  level:
    com:
      example:
        mybatisplus:
          mapper: debug
